---

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8011/eureka/
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
      
  instance:
    appname: myEurekaClient
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
    application:
        name: myEurekaClient

    

server:
  port: 8020
        